stages:
  - build
  - test

build-job:
  stage: build
  image: maven:3.9.6-eclipse-temurin-21
  script:
    - mvn clean compile
  artifacts:
    paths:
      - target/

unit-tests:
  stage: test
  image: maven:3.9.6-eclipse-temurin-21
  script:
    - mvn test
  only:
    - branches
