name: Java CI with Maven

on:
  push:
    branches: [ "**" ]
    
jobs: 
  compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Compile with Maven
      run: mvn clean compile
